Repository jorge07/symfony-5-es-cqrs-boilerplate, pull requests merged in 2020-06, with the labels that each got.

#159 [Windows] fix: allow HTTP requests to be debugged
  README.md
  doc/docker-php-interpreter.png
  doc/xdebug-validation.png
  etc/dev/docker-compose.windows.yml
  etc/dev/docker-compose.yml
  etc/dev/nginx/nginx.conf
  etc/dev/php/docker-xdebug.ini
  makefile
Labels: on hold

#164 API doc - invalid response for endpoint
  src/UI/Http/Rest/Controller/Event/GetEventsController.php
Labels: bug

#166 Improve docker performance and allowing public php files in dev env
  docker-compose.yml
  etc/dev/nginx/nginx.conf
Labels: enhancement
